name: Deploy to Firebase Hosting on Master

'on':
  push:
    branches:
      - master

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    environment: live-preview
    steps:
      - uses: actions/checkout@v2
      - env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_RO_TOKEN }}
        run: yarn && make build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HU_HUMA_COM_PUBLIC_WEBSITES }}'
          projectId: hu-huma-com-public-websites
          target: huma-docs-preview
          channelId: live
