name: Deploy to Firebase Hosting on PR

on: pull_request

# cancel in-progress workflows instances for the same PR
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

# => in case later, somebody is interested in deploying by comment
  # issue_comment:
  #   types: [created]
  # if: ${{ contains(github.event.comment.html_url, '/pull/') && contains(github.event.comment.body, '/deploy-pr-preview') }}

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    environment: pr-preview
    steps:
      - uses: actions/checkout@v2
      - env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_RO_TOKEN }}
        run: yarn && make build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HU_HUMA_COM_PUBLIC_WEBSITES }}'
          projectId: hu-huma-com-public-websites
          target: huma-docs-preview
