name: Deploy to Firebase Hosting on PR comment

on:
  pull_request: 
  issue_comment:
    types: [created]

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event.issue.pull_request != '' && contains(github.event.comment.body, '/deploy-pr-preview') }}
    runs-on: ubuntu-latest
    #environment: pr-preview
    steps:
      - uses: actions/checkout@v2
      - env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGE_RO_TOKEN }}
        run: echo 'test' #yarn && make build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HU_HUMA_COM_PUBLIC_WEBSITES }}'
          projectId: hu-huma-com-public-websites
          target: huma-docs-preview
